name: spliit

volumes:
  db-data:

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: kvdomingo/spliit
    restart: unless-stopped
    working_dir: /app
    entrypoint:
      - /bin/bash
      - -euxo
      - pipefail
      - -c
    command:
      - bun install && exec bun run dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      POSTGRES_PRISMA_URL: postgresql://postgres:postgres@db:5432
      POSTGRES_URL_NON_POOLING: postgresql://postgres:postgres@db:5432
      NEXT_PUBLIC_DEFAULT_CURRENCY_SYMBOL: '₱'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      start_period: 10s
      interval: 5s
      timeout: 3s
      retries: 5
